### PR TITLE
Text editor.

### PR DESCRIPTION
**Pull request by ComputerNerd**
As requested here is the pull request early.

### CODE REVIEW

**Comment by gbl08ma** [comment]
What's the progress with this? As I said before, I don't want to press you into writing a text editor, and it's perfectly understandable if you have lost interest, I just want to know what I can count with for the next release.

**Comment by ComputerNerd** [comment]
I have not done anything on it for quite some time. I have updated my gist to the current progress that I have made on it https://gist.github.com/ComputerNerd/411f38726467ee519afe.

This is a mere matter of forgetting. If I did not want to do the text editor I would have told you so. I do want to do this and my goal is to dedicate a day to do this.

I am going to be busy until May 13. Thus, I have decided to work on the text editor starting May 14.

**Comment by gbl08ma** [comment]
So how is the work on the editor going? Or did you get busier than you initially expected?

**Comment by gbl08ma** [comment]
I'm closing this, as I ended up developing my own text editor which uses the text editing facilities in the OS plus a custom rendering and cursor control engine, for supporting multiple lines and the 18px font.

**Pull request closed without merging**
